# примеры API-запросов
# admin_token = 61da64e0c2c82549bfeb463e142b7879c50e0afc
# golovin_token = 6efb8941e4db8aaebf4636a6b81d4ed5286b9993

@baseUrl = http://127.0.0.1:8000/api

###
# получаем список всех новостей
GET {{baseUrl}}/news/
Content-Type: application/json 

###
# создаем новость админом(не пользователем)
POST {{baseUrl}}/news/
Content-Type: application/json
Authorization: Token 61da64e0c2c82549bfeb463e142b7879c50e0afc

{
  "title": "About a lion",
  "text": "We feed our lion",
  "likes": [1]
}

###
# создаем новость пользователем(не адимном)
POST {{baseUrl}}/news/
Content-Type: application/json
Authorization: Token 6efb8941e4db8aaebf4636a6b81d4ed5286b9993

{
  "title": "About a bear",
  "text": "We feed our bear",
  "likes": [1]
}

###
# меняем новость пользователя от имени админа
PUT {{baseUrl}}/news/4/
Content-Type: application/json
Authorization: Token 61da64e0c2c82549bfeb463e142b7879c50e0afc

{
  "title": "About a BEAR",
  "text": "We feed our BEAR",
  "likes": [1]
}

###

# пробуем меняем новость админа от имени пользователя
PUT {{baseUrl}}/news/1/
Content-Type: application/json
Authorization: Token 6efb8941e4db8aaebf4636a6b81d4ed5286b9993

{
  "title": "About a BEAR",
  "text": "We feed our BEAR"
}

###

###
# удаляем новость пользователя от имени админа
DELETE {{baseUrl}}/news/11/
Content-Type: application/json
Authorization: Token 61da64e0c2c82549bfeb463e142b7879c50e0afc

{
  "title": "About a BEAR",
  "text": "We feed our BEAR",
  "likes": [1]
}

###

# пробуем удалить новость админа от имени пользователя
DELETE {{baseUrl}}/news/1/
Content-Type: application/json
Authorization: Token 6efb8941e4db8aaebf4636a6b81d4ed5286b9993

{
  "title": "About a BEAR",
  "text": "We feed our BEAR"
}

###
# получаем список всех комментов
GET {{baseUrl}}/comment/
Content-Type: application/json 

###
# создаем коммент от имени пользователя
POST {{baseUrl}}/comment/
Content-Type: application/json
Authorization: Token 6efb8941e4db8aaebf4636a6b81d4ed5286b9993

{   
    "text": "golovin's comment",
    "news": 2
}

###
# создаем коммент от имени админа
POST {{baseUrl}}/comment/
Content-Type: application/json
Authorization: Token 61da64e0c2c82549bfeb463e142b7879c50e0afc

{   
    "text": "admin's comment",
    "news": 2
}

###
# пробуем удалить коммент админа от имени пользователя
DELETE {{baseUrl}}/comment/7/
Content-Type: application/json
Authorization: Token 6efb8941e4db8aaebf4636a6b81d4ed5286b9993

###
#  удаляем коммент пользователя от имени админа
DELETE {{baseUrl}}/comment/4/
Content-Type: application/json
Authorization: Token 6efb8941e4db8aaebf4636a6b81d4ed5286b9993

###
# создаем лайк
POST {{baseUrl}}/like/
Content-Type: application/json
Authorization: Token 6efb8941e4db8aaebf4636a6b81d4ed5286b9993

{
  "news": 1
}

###
# удаляем лайк
DELETE {{baseUrl}}/like/1/
Content-Type: application/json
Authorization: Token 6efb8941e4db8aaebf4636a6b81d4ed5286b9993
